/**
 * Gerrit 评论写操作工具集 (REST 通道，v1.0.0)。
 *
 * 端点：
 *   - 单次 review：POST /changes/{id}/revisions/{rev}/review
 *     接受 ReviewInput body：{ message?, tag?, notify?, comments?, labels? }
 *   - addReviewComment / replyInlineComment / markCommentResolved 都是该端点的不同入参组合
 *   - submitReviewReply 在一次调用中合并 cover message + 多条 inline + label
 *
 * 与 v0.x SSH 通道相比的改进：
 *   - REST 直接接受 in_reply_to=<uuid> 字段，能精确串联到历史评论形成 thread
 *   - 不需要 Buffer 注入 stdin（fetch body 即标准 JSON）
 *
 * 行为契约保留：
 *   - 评论文本空白校验（Property 12）
 *   - 错误消息保留 change_id / file / line（Property 5）
 *   - 单批 inline ≤ 50（防止超大 payload）
 *   - patchset-level 评论 file === "/PATCHSET_LEVEL"，不带 line
 */

import { gerritPost } from "../http-client.js";
import { StructuredError } from "../errors.js";
import { queryChange } from "./query.js";

// =============================================================================
// 常量
// =============================================================================

const COMMENT_MESSAGE_MAX_CHARS = 16384;
const MAX_INLINE_REPLIES_PER_BATCH = 50;
const KNOWN_LABELS = ["Code-Review", "Verified"];
const NOTIFY_VALUES = ["NONE", "OWNER", "OWNER_REVIEWERS", "ALL"] as const;
type NotifyLevel = (typeof NOTIFY_VALUES)[number];

// =============================================================================
// REST API 入参类型（ReviewInput）
// =============================================================================

interface ReviewInput {
  message?: string;
  tag?: string;
  notify?: NotifyLevel;
  comments?: Record<string, ReviewInlineComment[]>;
  labels?: Record<string, number>;
}

interface ReviewInlineComment {
  /** 行号；patchset-level 评论不传 */
  line?: number;
  /** 多行评论的范围 */
  range?: {
    start_line: number;
    start_character: number;
    end_line: number;
    end_character: number;
  };
  message: string;
  unresolved?: boolean;
  /** 父评论 uuid */
  in_reply_to?: string;
  /** 1=REVISION（新版本），0=PARENT（旧版本） */
  side?: number;
}

// =============================================================================
// 内部辅助
// =============================================================================

function validateCommentMessage(message: string, ctx: string = "评论文本"): void {
  if (typeof message !== "string" || message.trim().length === 0) {
    throw new StructuredError(
      "internal_error",
      `${ctx}不可为空（trim 后长度为 0）`,
    );
  }
  if (message.length > COMMENT_MESSAGE_MAX_CHARS) {
    throw new StructuredError(
      "internal_error",
      `${ctx}超出 ${COMMENT_MESSAGE_MAX_CHARS} 字符上限`,
    );
  }
}

/**
 * 解析 patch set；调用方未提供时通过 queryChange 拿当前 patch set。
 *
 * REST 端点接受字符串 "current" 或具体数字。本函数返回数字便于上层记录。
 */
async function resolvePatchSet(
  changeId: string,
  patchSet: number | undefined,
): Promise<number> {
  if (typeof patchSet === "number" && patchSet > 0) return patchSet;
  const change = await queryChange(changeId);
  if (!change.current_patch_set) {
    throw new StructuredError(
      "internal_error",
      `Change ${changeId} 缺少 current_patch_set`,
    );
  }
  return change.current_patch_set;
}

/**
 * 提交 ReviewInput 到 Gerrit。
 *
 * 端点：POST /a/changes/{id}/revisions/{patchSet}/review
 */
async function submitReview(
  changeId: string,
  patchSet: number,
  body: ReviewInput,
): Promise<unknown> {
  const path = `/changes/${encodeURIComponent(changeId)}/revisions/${patchSet}/review`;
  return await gerritPost(path, body);
}

// =============================================================================
// 1. addReviewComment（cover-level 评论）
// =============================================================================

/**
 * 向 Change 添加 review-cover 级评论（无 inline）。
 *
 * @throws StructuredError("internal_error") message 校验失败
 */
export async function addReviewComment(args: {
  change_id: string;
  message: string;
  patch_set?: number;
}): Promise<{ ok: true; change_id: string; patch_set: number }> {
  validateCommentMessage(args.message);
  const patchSet = await resolvePatchSet(args.change_id, args.patch_set);

  await submitReview(args.change_id, patchSet, {
    message: args.message,
    tag: "autogenerated:gerrit-mcp-server:add_review_comment",
    notify: "OWNER",
  });

  return { ok: true, change_id: args.change_id, patch_set: patchSet };
}

// =============================================================================
// 2. replyInlineComment（单条 inline 回复）
// =============================================================================

/**
 * 在指定 file+line 上发布 inline 评论。
 *
 * REST 通道下相比 SSH 多了一个能力：可以传 in_reply_to=<uuid> 精确串联到历史评论。
 *
 * @throws StructuredError("internal_error") message 校验失败 / file 为空 / line 非法
 */
export async function replyInlineComment(args: {
  change_id: string;
  file: string;
  line: number;
  message: string;
  unresolved?: boolean;
  patch_set?: number;
  in_reply_to?: string;
}): Promise<{
  ok: true;
  change_id: string;
  file: string;
  line: number;
  patch_set: number;
}> {
  validateCommentMessage(args.message);

  if (typeof args.file !== "string" || args.file.trim().length === 0) {
    throw new StructuredError("internal_error", "file 不可为空");
  }
  const isPatchsetLevel = args.file === "/PATCHSET_LEVEL";

  if (!isPatchsetLevel) {
    if (!Number.isInteger(args.line) || args.line < 0) {
      throw new StructuredError(
        "internal_error",
        `line 必须为非负整数: ${args.line}`,
      );
    }
  }

  const patchSet = await resolvePatchSet(args.change_id, args.patch_set);

  const inline: ReviewInlineComment = {
    message: args.message,
    unresolved: args.unresolved ?? true,
  };
  if (!isPatchsetLevel) inline.line = args.line;
  if (args.in_reply_to) inline.in_reply_to = args.in_reply_to;

  await submitReview(args.change_id, patchSet, {
    tag: "autogenerated:gerrit-mcp-server:reply_inline_comment",
    notify: "OWNER",
    comments: {
      [args.file]: [inline],
    },
  });

  return {
    ok: true,
    change_id: args.change_id,
    file: args.file,
    line: args.line,
    patch_set: patchSet,
  };
}

// =============================================================================
// 3. markCommentResolved
// =============================================================================

/**
 * 把指定 file+line 上的 inline 评论标记为 resolved。
 */
export async function markCommentResolved(args: {
  change_id: string;
  file: string;
  line: number;
  message?: string;
  patch_set?: number;
}): Promise<{
  ok: true;
  change_id: string;
  file: string;
  line: number;
  patch_set: number;
}> {
  if (typeof args.file !== "string" || args.file.trim().length === 0) {
    throw new StructuredError("internal_error", "file 不可为空");
  }
  if (args.file !== "/PATCHSET_LEVEL") {
    if (!Number.isInteger(args.line) || args.line < 0) {
      throw new StructuredError(
        "internal_error",
        `line 必须为非负整数: ${args.line}`,
      );
    }
  }

  const finalMessage =
    typeof args.message === "string" && args.message.trim().length > 0
      ? args.message
      : "已标记为 resolved";

  return replyInlineComment({
    change_id: args.change_id,
    file: args.file,
    line: args.line,
    message: finalMessage,
    unresolved: false,
    patch_set: args.patch_set,
  });
}

// =============================================================================
// 4. submitReviewReply（★ Web UI "REPLY" 按钮的批量等价）
// =============================================================================

export interface InlineReplyEntry {
  /** 文件路径；"/PATCHSET_LEVEL" 表示 patchset-level 评论 */
  file: string;
  /** 行号；patchset-level 不传，具体文件必须传非负整数 */
  line?: number;
  message: string;
  /** 是否标记 unresolved；undefined 等价 false */
  unresolved?: boolean;
  /** 可选父评论 uuid */
  in_reply_to?: string;
}

/**
 * 批量提交 review 回复，对应 Web UI "REPLY" 按钮。
 *
 * REST 通道单次 POST /a/changes/{id}/revisions/{rev}/review 一次性提交：
 *   - 多条 inline 回复（含 unresolved + in_reply_to）
 *   - 可选 cover message
 *   - 可选 label 设置（如 Code-Review +1）
 *   - 单次通知（默认 OWNER）
 */
export async function submitReviewReply(args: {
  change_id: string;
  inline_replies: InlineReplyEntry[];
  cover_message?: string;
  labels?: Record<string, number>;
  notify?: NotifyLevel;
  patch_set?: number;
}): Promise<{
  ok: true;
  change_id: string;
  patch_set: number;
  submitted_inline_count: number;
  cover_message_included: boolean;
  labels_applied: Record<string, number> | null;
  notify: NotifyLevel;
}> {
  // ① inline_replies 非空数组
  if (!Array.isArray(args.inline_replies) || args.inline_replies.length === 0) {
    throw new StructuredError(
      "internal_error",
      "inline_replies 必须是非空数组（至少包含 1 条 inline 回复）。如仅需添加 cover message，请改用 add_review_comment。",
    );
  }
  if (args.inline_replies.length > MAX_INLINE_REPLIES_PER_BATCH) {
    throw new StructuredError(
      "internal_error",
      `inline_replies 超出单批 ${MAX_INLINE_REPLIES_PER_BATCH} 条上限（实际 ${args.inline_replies.length}）。请分批提交。`,
    );
  }

  // ② cover_message
  let coverMessage: string | undefined;
  if (typeof args.cover_message === "string") {
    validateCommentMessage(args.cover_message, "cover_message");
    coverMessage = args.cover_message;
  }

  // ③ notify
  const notify: NotifyLevel = args.notify ?? "OWNER";
  if (!NOTIFY_VALUES.includes(notify)) {
    throw new StructuredError(
      "internal_error",
      `notify 取值非法: ${notify}（合法值 ${NOTIFY_VALUES.join(" / ")}）`,
    );
  }

  // ④ labels 校验
  let labelsValidated: Record<string, number> | null = null;
  if (args.labels && typeof args.labels === "object") {
    labelsValidated = {};
    for (const [name, value] of Object.entries(args.labels)) {
      if (typeof name !== "string" || name.trim().length === 0) {
        throw new StructuredError("internal_error", "label 名不可为空");
      }
      if (!Number.isInteger(value) || value < -2 || value > 2) {
        throw new StructuredError(
          "internal_error",
          `label '${name}' 值越界（必须为 -2..+2 整数）: ${value}`,
        );
      }
      labelsValidated[name] = value;
    }
    if (Object.keys(labelsValidated).length === 0) labelsValidated = null;
  }

  // ⑤ inline_replies 元素校验 + 按 file 分组
  const groupedByFile: Record<string, ReviewInlineComment[]> = {};
  for (let i = 0; i < args.inline_replies.length; i++) {
    const entry = args.inline_replies[i];
    if (typeof entry !== "object" || entry === null) {
      throw new StructuredError(
        "internal_error",
        `inline_replies[${i}] 不是对象`,
      );
    }
    if (typeof entry.file !== "string" || entry.file.trim().length === 0) {
      throw new StructuredError(
        "internal_error",
        `inline_replies[${i}].file 不可为空`,
      );
    }
    validateCommentMessage(entry.message, `inline_replies[${i}].message`);

    const isPatchsetLevel = entry.file === "/PATCHSET_LEVEL";
    if (isPatchsetLevel) {
      if (entry.line !== undefined) {
        throw new StructuredError(
          "internal_error",
          `inline_replies[${i}]: patchset-level 评论不可携带 line 字段`,
        );
      }
    } else {
      if (!Number.isInteger(entry.line) || (entry.line as number) < 0) {
        throw new StructuredError(
          "internal_error",
          `inline_replies[${i}].line 必须为非负整数（具体文件评论）；当前值 ${entry.line}`,
        );
      }
    }

    const inline: ReviewInlineComment = {
      message: entry.message,
      unresolved: entry.unresolved ?? false, // 默认 false：标记为 resolved
    };
    if (!isPatchsetLevel) inline.line = entry.line;
    if (entry.in_reply_to) inline.in_reply_to = entry.in_reply_to;

    if (!groupedByFile[entry.file]) groupedByFile[entry.file] = [];
    groupedByFile[entry.file].push(inline);
  }

  // ⑥ patch set
  const patchSet = await resolvePatchSet(args.change_id, args.patch_set);

  // ⑦ 提交
  const reviewInput: ReviewInput = {
    tag: "autogenerated:gerrit-mcp-server:submit_review_reply",
    notify,
    comments: groupedByFile,
  };
  if (coverMessage !== undefined) reviewInput.message = coverMessage;
  if (labelsValidated !== null) reviewInput.labels = labelsValidated;

  await submitReview(args.change_id, patchSet, reviewInput);

  return {
    ok: true,
    change_id: args.change_id,
    patch_set: patchSet,
    submitted_inline_count: args.inline_replies.length,
    cover_message_included: coverMessage !== undefined,
    labels_applied: labelsValidated,
    notify,
  };
}
