/**
 * Gerrit 读操作工具集。
 *
 * 暴露 4 个工具函数（在 src/index.ts 中注册为 MCP 工具）：
 *   - queryChange:        GET /changes/{id}?o=CURRENT_REVISION&o=DETAILED_LABELS
 *   - listBranches:       GET /projects/{project}/branches/
 *   - getChangeComments:  GET /changes/{id}/comments + GET /changes/{id}/messages
 *   - searchChanges:      GET /changes/?q={query}&n={limit}
 *
 * 设计要点：
 *   - 路径参数（change_id、project）通过 `encodeURIComponent` 编码，覆盖 `~` `+` `@` 等 Gerrit 三元组特殊字符
 *   - commit message 中 `Zmind#(\d+)` 全局正则提取 issue_id 列表；多个匹配按出现顺序保留（不去重）
 *   - `list_branches` 空匹配返回 `[]` 而非抛异常（Property 6）；调用方在 index.ts 注册时拼接 note
 *   - `get_change_comments` 合并 inline 评论 + review 级 messages，按 created 升序排序，
 *     时间相同时按 id 字典序作次级排序（Property 7）
 *   - HTTP 错误（401/403/404/5xx）由底层 `gerritGet` 透传 StructuredError；本层不重新封装
 *     （Property 5 的标识符注入由 `wrapToolHandler` 在 index.ts 注册时统一处理）
 */

import { gerritGet } from "../http-client.js";
import type { GerritBranch, GerritChange, GerritComment } from "../types.js";

// =============================================================================
// Gerrit 响应模型（仅取本工具用到的字段）
// =============================================================================

/**
 * Gerrit ChangeInfo 响应。
 *
 * 文档：https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-info
 *
 * 字段语义：
 *   - id:               project~branch~Change-Id 三元组（URL 编码后的）
 *   - change_id:        仅 Change-Id（如 Ixxx...）
 *   - _number:          Change 数字编号
 *   - current_revision: 当前 revision 的 commit SHA-1
 *   - revisions:        各 revision 信息字典（key 是 commit SHA）
 */
interface GerritChangeInfo {
  id: string;
  change_id: string;
  _number: number;
  subject: string;
  status: string;
  project: string;
  branch: string;
  topic?: string;
  owner?: { _account_id?: number; name?: string; email?: string };
  current_revision?: string;
  revisions?: Record<string, GerritRevisionInfo>;
}

interface GerritRevisionInfo {
  _number?: number;
  commit?: { message?: string };
  ref?: string;
}

interface GerritBranchInfo {
  ref: string;
  revision: string;
  /** Gerrit 在某些版本中提供 `web_links`、`can_delete` 等字段；仅取必要字段。 */
}

/** Gerrit `GET /changes/{id}/comments` 响应：以文件路径为 key 的 comment 列表字典。 */
type GerritCommentMap = Record<string, GerritCommentInfo[]>;

interface GerritCommentInfo {
  id: string;
  /** ISO 8601 时间字符串。 */
  updated?: string;
  /** Gerrit 实际返回 created 字段，但部分版本仅提供 updated。 */
  created?: string;
  message?: string;
  unresolved?: boolean;
  line?: number;
  patch_set?: number;
  in_reply_to?: string;
  author?: { _account_id?: number; name?: string; email?: string };
}

interface GerritChangeMessageInfo {
  id: string;
  date: string; // ISO 8601
  message: string;
  _revision_number?: number;
  author?: { _account_id?: number; name?: string; email?: string };
  /** Gerrit `tag` 字段标记机器生成评论（如 `autogenerated:gerrit:newPatchSet`），本工具不过滤 */
  tag?: string;
}

// =============================================================================
// 内部辅助
// =============================================================================

/** 从 commit message 中按出现顺序提取 `Zmind#(\d+)` 中的数字 ID 列表。 */
function extractZmindIssueIds(commitMessage: string | undefined | null): number[] {
  if (typeof commitMessage !== "string" || commitMessage.length === 0) return [];
  const ids: number[] = [];
  // /g 标志保证 matchAll 返回所有匹配；不去重，保留 commit message 中的实际出现顺序
  for (const m of commitMessage.matchAll(/Zmind#(\d+)/g)) {
    const id = parseInt(m[1], 10);
    if (Number.isFinite(id)) ids.push(id);
  }
  return ids;
}

/** 拼接 Gerrit Change Web URL。 */
function buildChangeWebUrl(project: string, changeNumber: number): string {
  const baseUrl = (process.env.GERRIT_URL ?? "").replace(/\/+$/, "");
  // 若未配置 GERRIT_URL（理论不可达，因为 gerritGet 已校验），仍返回相对路径以避免空字符串拼接
  const projectSegment = encodeURI(project);
  return `${baseUrl}/c/${projectSegment}/+/${changeNumber}`;
}

/**
 * 从 Gerrit ChangeInfo 中提取当前 patch set 编号。
 *
 * 优先 `revisions[current_revision]._number`；缺失时回退 0（design 9: GerritChange.current_patch_set）。
 */
function extractCurrentPatchSet(info: GerritChangeInfo): number {
  if (info.current_revision && info.revisions) {
    const rev = info.revisions[info.current_revision];
    if (rev && typeof rev._number === "number") return rev._number;
  }
  return 0;
}

/**
 * 把 Gerrit ChangeInfo 映射为本服务的 GerritChange 类型。
 *
 * @param info   Gerrit 原始响应
 * @param commitMessage  当前 revision 的 commit message（可选；无则 zmind_issue_ids 为空数组）
 */
function mapToGerritChange(info: GerritChangeInfo, commitMessage?: string): GerritChange {
  const message =
    commitMessage ??
    (info.current_revision && info.revisions
      ? info.revisions[info.current_revision]?.commit?.message
      : undefined);

  return {
    id: info.id,
    change_id: info.change_id,
    number: info._number,
    subject: info.subject,
    status: (info.status as GerritChange["status"]) ?? "NEW",
    project: info.project,
    branch: info.branch,
    topic: info.topic,
    owner: {
      name: info.owner?.name ?? "",
      email: info.owner?.email,
    },
    current_revision: info.current_revision,
    current_patch_set: extractCurrentPatchSet(info),
    zmind_issue_ids: extractZmindIssueIds(message),
    web_url: buildChangeWebUrl(info.project, info._number),
  };
}

// =============================================================================
// 1. queryChange
// =============================================================================

/**
 * 查询单个 Gerrit Change 的详情。
 *
 * @param changeId Change-Id 字符串（Ixxx...）、Change Number 或 project~branch~changeId 三元组。
 *                 调用方负责非空校验（zod schema `min(1)`）。
 *
 * @returns 完整的 GerritChange，包含从 commit message 提取的 zmind_issue_ids。
 * @throws  StructuredError 由底层 gerritGet 透传（401/403/404/timeout/network 等）
 */
export async function queryChange(changeId: string): Promise<GerritChange> {
  const path = `/changes/${encodeURIComponent(changeId)}?o=CURRENT_REVISION&o=DETAILED_LABELS`;
  const info = await gerritGet<GerritChangeInfo>(path);
  return mapToGerritChange(info);
}

// =============================================================================
// 2. listBranches
// =============================================================================

/** list_branches 在空匹配时返回的特殊响应（与 GerritBranch[] 平级供 wrapper 直接序列化）。 */
export interface ListBranchesResult {
  branches: GerritBranch[];
  /** 当 pattern 提供且匹配为空时，附加说明。 */
  note?: string;
}

/**
 * 列出指定 project 的分支，最多 500 条；当 pattern 提供时进行客户端 substring 过滤（大小写敏感）。
 *
 * @param project Gerrit project 名（必需，非空由 zod 校验）
 * @param pattern 可选过滤模式（substring 匹配），未提供时返回全部分支
 *
 * @returns ListBranchesResult；空匹配时 branches=[] 且附带 note（Property 6）
 * @throws  StructuredError 由底层 gerritGet 透传（404 = project 不存在等）
 */
export async function listBranches(
  project: string,
  pattern?: string,
): Promise<ListBranchesResult> {
  const path = `/projects/${encodeURIComponent(project)}/branches/`;
  const all = await gerritGet<GerritBranchInfo[]>(path);

  // 防御：Gerrit 在某些异常状态下可能返回 null 而非数组
  const safeAll: GerritBranchInfo[] = Array.isArray(all) ? all : [];

  // 客户端过滤：substring 匹配（大小写敏感）；500 条上限按 ref 序列截断
  const filtered = pattern
    ? safeAll.filter((b) => typeof b.ref === "string" && b.ref.includes(pattern))
    : safeAll;
  const capped = filtered.slice(0, 500);

  const branches: GerritBranch[] = capped.map((b) => ({
    ref: b.ref,
    revision: b.revision,
    name: b.ref.startsWith("refs/heads/") ? b.ref.slice("refs/heads/".length) : b.ref,
  }));

  if (pattern && branches.length === 0) {
    return {
      branches: [],
      note: `no branches matched the pattern: ${pattern}`,
    };
  }

  return { branches };
}

// =============================================================================
// 3. getChangeComments
// =============================================================================

/**
 * 获取一个 Change 的全部评论（inline + review 级），合并后按时间升序排序。
 *
 * 调用 Gerrit 两个端点：
 *   1. GET /changes/{id}/comments  → 文件路径分组的 inline 评论 map
 *   2. GET /changes/{id}/messages  → review 级 messages 列表（path/line 字段缺失）
 *
 * 排序规则（Property 7）：
 *   1. 主键：created 字符串（ISO 8601 升序，同字符串字典序即时间序）
 *   2. 次级：id 字典序（确保同时间戳评论顺序稳定）
 *
 * @throws StructuredError 由底层 gerritGet 透传
 */
export async function getChangeComments(changeId: string): Promise<GerritComment[]> {
  const encodedId = encodeURIComponent(changeId);

  const [commentsMap, messages] = await Promise.all([
    gerritGet<GerritCommentMap>(`/changes/${encodedId}/comments`),
    gerritGet<GerritChangeMessageInfo[]>(`/changes/${encodedId}/messages`),
  ]);

  const merged: GerritComment[] = [];

  // ① 合并 inline 评论：把 commentsMap 拍平为单个数组，每条加上 path 字段
  if (commentsMap && typeof commentsMap === "object") {
    for (const [path, list] of Object.entries(commentsMap)) {
      if (!Array.isArray(list)) continue;
      for (const c of list) {
        merged.push({
          id: c.id,
          author: {
            name: c.author?.name ?? "",
            email: c.author?.email,
          },
          // Gerrit 实际返回 `updated` 字段，但 design.md GerritComment.created 沿用此值
          created: c.updated ?? c.created ?? "",
          message: c.message ?? "",
          unresolved: c.unresolved === true,
          path,
          line: c.line,
          patch_set: c.patch_set,
          in_reply_to: c.in_reply_to,
        });
      }
    }
  }

  // ② 合并 review 级 messages：path/line 字段缺省（review 评论不归属具体文件）
  if (Array.isArray(messages)) {
    for (const m of messages) {
      merged.push({
        id: m.id,
        author: {
          name: m.author?.name ?? "",
          email: m.author?.email,
        },
        created: m.date ?? "",
        message: m.message,
        unresolved: false, // review 级 message 无 unresolved 概念
        // path/line 故意省略，保持 GerritComment 类型可选字段为 undefined
        patch_set: m._revision_number,
      });
    }
  }

  // ③ 按时间升序，相同时间按 id 字典序
  merged.sort((a, b) => {
    if (a.created < b.created) return -1;
    if (a.created > b.created) return 1;
    if (a.id < b.id) return -1;
    if (a.id > b.id) return 1;
    return 0;
  });

  return merged;
}

// =============================================================================
// 4. searchChanges
// =============================================================================

/**
 * 按 Gerrit 查询语法搜索 Change（如 `topic:332669 status:merged branch:master`）。
 *
 * @param query Gerrit search syntax 字符串
 * @param limit 返回数量上限（默认 25，最大 100；上限由 zod schema 在 index.ts 强制）
 *
 * @returns 映射后的 GerritChange 数组；未提供 CURRENT_REVISION 选项时部分字段（current_revision、
 *          current_patch_set、zmind_issue_ids）可能为空/0/[]，与 design.md 约定一致（搜索场景不需详情）
 * @throws  StructuredError 由底层 gerritGet 透传
 */
export async function searchChanges(
  query: string,
  limit: number = 25,
): Promise<GerritChange[]> {
  // Gerrit `n` 参数控制返回数量；不指定 `o=CURRENT_REVISION` 以保持响应轻量（搜索结果常用于"列表展示"场景）
  const params = new URLSearchParams();
  params.set("q", query);
  params.set("n", String(limit));
  const path = `/changes/?${params.toString()}`;

  const list = await gerritGet<GerritChangeInfo[]>(path);
  if (!Array.isArray(list)) return [];

  return list.map((info) => mapToGerritChange(info));
}
