/**
 * Reviewer / Code-Review 标签管理工具 (REST 通道，v1.0.0)。
 *
 * 端点：
 *   - addReviewer:    POST /a/changes/{id}/reviewers, body { reviewer: <emailOrUsername> }
 *   - removeReviewer: DELETE /a/changes/{id}/reviewers/{accountIdentifier}
 *   - setReviewLabel: POST /a/changes/{id}/revisions/{rev}/review, body { labels: { name: value } }
 *
 * 输入校验：
 *   - reviewer 非空（trim 后长度 > 0）
 *   - label 非空、value 必须是 [-2, +2] 整数（Property 13）
 *
 * 错误处理：
 *   - HTTP 错误统一映射到 StructuredError（由 http-client.ts 处理）
 *   - 错误消息保留 change_id / reviewer / label（Property 5，由 wrapToolHandler 注入）
 */

import { gerritPost, gerritDelete } from "../http-client.js";
import { StructuredError } from "../errors.js";
import { queryChange } from "./query.js";

// =============================================================================
// 1. addReviewer
// =============================================================================

/**
 * 向 Change 添加一名 Reviewer。
 *
 * 端点：POST /a/changes/{id}/reviewers
 * Body: { "reviewer": "alice@example.com" }
 *
 * Gerrit 接受 email / username / numeric account-id 任一形式。
 *
 * @throws StructuredError("internal_error") reviewer 为空或仅含空白
 */
export async function addReviewer(args: {
  change_id: string;
  reviewer: string;
}): Promise<{ ok: true; change_id: string; reviewer: string }> {
  if (typeof args.reviewer !== "string" || args.reviewer.trim().length === 0) {
    throw new StructuredError("internal_error", "Reviewer 标识符不可为空");
  }
  const reviewer = args.reviewer.trim();

  const path = `/changes/${encodeURIComponent(args.change_id)}/reviewers`;
  await gerritPost(path, { reviewer });

  return {
    ok: true,
    change_id: args.change_id,
    reviewer,
  };
}

// =============================================================================
// 2. removeReviewer
// =============================================================================

/**
 * 从 Change 移除一名 Reviewer。
 *
 * 端点：DELETE /a/changes/{id}/reviewers/{accountIdentifier}
 *
 * accountIdentifier 接受 username / email / "Self" / numeric account-id。
 */
export async function removeReviewer(args: {
  change_id: string;
  reviewer: string;
}): Promise<{ ok: true; change_id: string; reviewer: string }> {
  if (typeof args.reviewer !== "string" || args.reviewer.trim().length === 0) {
    throw new StructuredError("internal_error", "Reviewer 标识符不可为空");
  }
  const reviewer = args.reviewer.trim();

  const path = `/changes/${encodeURIComponent(args.change_id)}/reviewers/${encodeURIComponent(reviewer)}`;
  await gerritDelete(path);

  return {
    ok: true,
    change_id: args.change_id,
    reviewer,
  };
}

// =============================================================================
// 3. setReviewLabel
// =============================================================================

/**
 * 在 Change 当前 patch set 上设置一个标签值。
 *
 * 端点：POST /a/changes/{id}/revisions/{rev}/review
 * Body: { labels: { "Code-Review": +1 } }
 *
 * REST 接受字符串 "current" 作为 patch set 占位符（不像 SSH 必须传具体数字）；
 * 但为了能在响应里返回具体 patch set 编号，仍先 query 一次。
 *
 * @throws StructuredError("internal_error") label 为空 / value 超范围
 */
export async function setReviewLabel(args: {
  change_id: string;
  label: string;
  value: number;
}): Promise<{
  ok: true;
  change_id: string;
  label: string;
  value: number;
  patch_set: number;
}> {
  // 标签值范围（Property 13）
  if (!Number.isInteger(args.value) || args.value < -2 || args.value > 2) {
    throw new StructuredError(
      "internal_error",
      `标签值超出 -2 至 +2 范围: ${args.value}`,
    );
  }

  // 标签名非空 + 不含空格 / `=` 等
  if (typeof args.label !== "string" || args.label.trim().length === 0) {
    throw new StructuredError("internal_error", "标签名不可为空");
  }
  const labelTrimmed = args.label.trim();
  if (/[\s=`"'\\]/.test(labelTrimmed)) {
    throw new StructuredError(
      "internal_error",
      `标签名包含非法字符（不允许空格、=、引号、反引号、反斜杠）: ${labelTrimmed}`,
    );
  }

  const change = await queryChange(args.change_id);
  const patchSet = change.current_patch_set;

  const path = `/changes/${encodeURIComponent(args.change_id)}/revisions/${patchSet}/review`;
  await gerritPost(path, {
    tag: "autogenerated:gerrit-mcp-server:set_review_label",
    notify: "OWNER",
    labels: {
      [labelTrimmed]: args.value,
    },
  });

  return {
    ok: true,
    change_id: args.change_id,
    label: labelTrimmed,
    value: args.value,
    patch_set: patchSet,
  };
}
