/**
 * Gerrit NoteDb meta ref reader.
 *
 * 背景与设计依据（实证 2026-06，change 114401）：
 *   1. SSH `gerrit query --comments` 不返回评论的 uuid / unresolved / parentUuid 字段，
 *      因此无法用 SSH query 找出"哪些 thread 还 unresolved"或建立 in_reply_to 链路。
 *   2. 本环境 nginx 双层认证使 Gerrit REST `/a/...` 不可用。
 *   3. 第三条路径成立：Gerrit 把所有评论以 protobuf-as-JSON 的形式存在
 *      `refs/changes/<XX>/<change>/meta` 这个 git ref 里，**走 SSH git protocol 可以
 *      正常 fetch**（无 nginx 拦截）。
 *
 * NoteDb 数据结构（已实证）：
 *   - meta ref 上每个 commit 都是一次评论事件
 *   - 评论 JSON 文件以 patch set 的 commit SHA-1 为文件名
 *   - 文件内容是 `{"comments": [CommentRecord, ...]}`，CommentRecord 含完整
 *     {key.uuid, key.filename, lineNbr, range, author.id, message, parentUuid, unresolved, writtenOn, ...}
 *   - 后一次 commit 整体替换文件（每次 commit 持有"该 commit 时刻所有评论的全量快照"），
 *     所以**取 meta HEAD 上的文件即可拿当前最新评论集**
 *
 * 本模块只读，不改 NoteDb（Gerrit 的写入应通过 `gerrit review --json` 走标准 review API）。
 *
 * 关键约束：
 *   - 临时 git working dir 用完即删；进程崩溃时由操作系统的 tmp 清理回收
 *   - SSH key 未配置 / nginx 拦截等错误统一映射到 StructuredError（沿用 ssh-client.ts 的 mapSshError）
 *   - shard 计算严格按 Gerrit 规则 `last-2-digits.padStart(2, "0")`
 */

import { spawn } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { StructuredError } from "./errors.js";
import { mapSshError, requireSshConfig } from "./ssh-client.js";

// =============================================================================
// 类型
// =============================================================================

/**
 * NoteDb 中单条评论的原始记录（与 git note 文件中的 JSON 对象 1:1 对应）。
 *
 * 字段命名遵从 Gerrit 服务端 protobuf 字段名（不是 REST API CommentInfo 的 camelCase）。
 */
export interface NoteDbCommentRecord {
  key: {
    uuid: string;
    filename: string; // "/PATCHSET_LEVEL" 或文件路径
    patchSetId: number;
  };
  /** 行号；patchset-level 评论为 0；具体文件评论从 1 开始 */
  lineNbr: number;
  /** 父评论 uuid（thread 链）；root 评论无此字段 */
  parentUuid?: string;
  /** 评论作者的 Gerrit account_id（数字 ID） */
  author: { id: number };
  /** Whether the comment must still be addressed; 一旦写入永不变 */
  unresolved: boolean;
  /** ISO 8601 时间戳，来自 Gerrit 服务端写入时刻 */
  writtenOn: string;
  message: string;
  /** range 信息（仅多行/选中范围评论才有） */
  range?: {
    startLine: number;
    startChar: number;
    endLine: number;
    endChar: number;
  };
  /** Gerrit tag（如 autogenerated:gerrit-mcp-server:...） */
  tag?: string;
  /** patch set 的 commit SHA */
  revId: string;
  /** Gerrit server 实例 ID */
  serverId: string;
  /** 1 = REVISION, 0 = PARENT（diff 的左/右侧） */
  side?: number;
}

/**
 * 解析后的 thread 视图：以 root 评论为入口，含完整子评论链。
 *
 * `is_unresolved` 按 Web UI 规则计算：thread 中按 writtenOn 升序排列后，
 * 最末一条评论的 unresolved 状态决定整个 thread 的状态。
 */
export interface NoteDbThread {
  root: NoteDbCommentRecord;
  /** 升序排列的所有评论（含 root 自己），按 writtenOn 时间序 */
  chain: NoteDbCommentRecord[];
  is_unresolved: boolean;
  /** 用于判断"thread 状态由哪条评论决定"——即 chain 的最后一条 */
  latest: NoteDbCommentRecord;
}

// =============================================================================
// 内部工具
// =============================================================================

/** Gerrit ref shard 规则：`refs/changes/<最后2位补零>/<change_num>/meta` */
function changeMetaRef(changeNumber: string | number): string {
  const num = String(changeNumber);
  if (!/^\d+$/.test(num)) {
    throw new StructuredError(
      "internal_error",
      `change_number 必须是数字字符串: ${changeNumber}`,
    );
  }
  // last-2 padding：如 "5" → "05"，"114401" → "01"
  const last2 = num.slice(-2).padStart(2, "0");
  return `refs/changes/${last2}/${num}/meta`;
}

/** 子进程执行 spawn，带超时与错误映射。返回 stdout/stderr/exitCode（不抛业务异常）。 */
function execChild(
  command: string,
  args: string[],
  cwd: string | undefined,
  timeoutMs: number,
): Promise<{ stdout: Buffer; stderr: Buffer; exitCode: number }> {
  return new Promise((resolve, reject) => {
    const proc = spawn(command, args, { cwd, stdio: ["pipe", "pipe", "pipe"] });
    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];
    let timedOut = false;
    let killTimer: NodeJS.Timeout | undefined;

    proc.stdout?.on("data", (c) => stdoutChunks.push(c));
    proc.stderr?.on("data", (c) => stderrChunks.push(c));
    proc.stdin?.end();

    const timer = setTimeout(() => {
      timedOut = true;
      try {
        proc.kill("SIGTERM");
      } catch {
        /* ignore */
      }
      killTimer = setTimeout(() => {
        try {
          proc.kill("SIGKILL");
        } catch {
          /* ignore */
        }
      }, 1000);
    }, timeoutMs);

    proc.on("error", (err) => {
      clearTimeout(timer);
      if (killTimer) clearTimeout(killTimer);
      reject(err);
    });

    proc.on("close", (code) => {
      clearTimeout(timer);
      if (killTimer) clearTimeout(killTimer);
      if (timedOut) {
        reject(
          new StructuredError(
            "request_timeout",
            `${command} 超时 (${timeoutMs}ms): ${command} ${args.join(" ")}`,
          ),
        );
        return;
      }
      resolve({
        stdout: Buffer.concat(stdoutChunks),
        stderr: Buffer.concat(stderrChunks),
        exitCode: code ?? -1,
      });
    });
  });
}

// =============================================================================
// 核心入口：fetchAndParseNoteDb
// =============================================================================

/**
 * Fetch the NoteDb meta ref for a given change and parse all comments at the
 * current latest state.
 *
 * 流程：
 *   1. mkdtemp 创建临时 git working dir
 *   2. git init -q
 *   3. git fetch ssh://...:29418/<project> refs/changes/XX/<num>/meta
 *   4. 用 git rev-list FETCH_HEAD 拿到从老到新的 commit 序列
 *   5. 从最新 commit 倒序找：第一个含有 `<patch_set_commit_sha>` 文件的 commit，
 *      即"NoteDb 写入该 patch set 的最新评论快照"
 *   6. JSON.parse 该文件内容
 *   7. 清理临时目录
 *
 * @param changeNumber       数字 change number（如 "114401"）
 * @param patchSetCommitSha  当前 patch set 的 commit SHA（NoteDb note 用它做文件名）
 * @param projectName        Gerrit project 名（如 "am30ap/platform/vendor/amlogic/common"）
 *
 * @returns 该 patch set 上的所有评论（NoteDbCommentRecord 数组）
 *
 * @throws StructuredError("network_error" / "permission_denied" / "not_found")
 *         - SSH 连接失败 / SSH key 未授权 / change 不存在或无权访问
 * @throws StructuredError("request_timeout")
 *         - git 子命令超时
 * @throws StructuredError("internal_error")
 *         - meta ref 上找不到 patch set 评论文件 / JSON 解析失败 / git init 失败
 */
export async function fetchAndParseNoteDb(args: {
  changeNumber: string | number;
  patchSetCommitSha: string;
  projectName: string;
}): Promise<NoteDbCommentRecord[]> {
  const cfg = requireSshConfig();
  const ref = changeMetaRef(args.changeNumber);
  const url = `ssh://${cfg.user}@${cfg.host}:${cfg.port}/${args.projectName}`;

  if (!/^[0-9a-f]{40}$/i.test(args.patchSetCommitSha)) {
    throw new StructuredError(
      "internal_error",
      `patchSetCommitSha 必须是 40 位 hex SHA-1: ${args.patchSetCommitSha}`,
    );
  }

  const tmp = await mkdtemp(join(tmpdir(), "gerrit-notedb-"));
  try {
    // ① git init
    const initRes = await execChild("git", ["init", "-q", tmp], undefined, cfg.timeoutMs);
    if (initRes.exitCode !== 0) {
      throw new StructuredError(
        "internal_error",
        `git init 失败 (exit ${initRes.exitCode}): ${initRes.stderr.toString("utf8")}`,
      );
    }

    // ② git fetch（这步是 SSH 通道，错误映射成 StructuredError）
    const fetchRes = await execChild(
      "git",
      ["-C", tmp, "fetch", "--quiet", url, ref],
      undefined,
      cfg.timeoutMs,
    );
    if (fetchRes.exitCode !== 0) {
      throw mapSshError(fetchRes.exitCode, fetchRes.stderr.toString("utf8"));
    }

    // ③ git log --pretty=format:%H FETCH_HEAD（最新在前）
    const logRes = await execChild(
      "git",
      ["-C", tmp, "log", "--pretty=format:%H", "FETCH_HEAD"],
      undefined,
      cfg.timeoutMs,
    );
    if (logRes.exitCode !== 0) {
      throw new StructuredError(
        "internal_error",
        `git log 失败 (exit ${logRes.exitCode}): ${logRes.stderr.toString("utf8")}`,
      );
    }
    const commits = logRes.stdout
      .toString("utf8")
      .split(/\r?\n/)
      .filter((s) => s.length > 0);
    if (commits.length === 0) {
      throw new StructuredError(
        "not_found",
        `meta ref 为空（无评论）: ${ref}`,
        404,
      );
    }

    // ④ 从最新 commit 倒序找第一个含 <patchSetCommitSha> 文件的 commit
    let noteJson: { comments?: NoteDbCommentRecord[] } | null = null;
    for (const sha of commits) {
      const showRes = await execChild(
        "git",
        ["-C", tmp, "show", `${sha}:${args.patchSetCommitSha}`],
        undefined,
        cfg.timeoutMs,
      );
      if (showRes.exitCode === 0 && showRes.stdout.length > 0) {
        try {
          noteJson = JSON.parse(showRes.stdout.toString("utf8"));
          break;
        } catch {
          // 该 commit 上的文件不是合法 JSON（理论不应发生），继续往前找
        }
      }
    }

    if (!noteJson) {
      throw new StructuredError(
        "not_found",
        `meta ref 上找不到 patch set 评论文件: ref=${ref} expected_file=${args.patchSetCommitSha}`,
        404,
      );
    }

    return Array.isArray(noteJson.comments) ? noteJson.comments : [];
  } finally {
    await rm(tmp, { recursive: true, force: true }).catch(() => {
      /* 临时目录清理失败不影响业务结果，操作系统的 tmp 清理会兜底 */
    });
  }
}

// =============================================================================
// 解析：构建 thread 视图
// =============================================================================

/**
 * 把扁平的评论数组按 parentUuid 重建成 thread 视图。
 *
 * 计算规则（与 Gerrit Web UI 一致）：
 *   1. parentUuid 缺省或不指向已知 uuid 的评论 → root
 *   2. 每个 root 沿着 child index 收集所有后代
 *   3. 整个链按 writtenOn 升序排列
 *   4. is_unresolved = chain[最后一条].unresolved
 *
 * 边界处理：
 *   - 若 parentUuid 指向不存在的 uuid（数据损坏），把该评论也当 root 处理
 *   - 循环引用（理论不应发生）通过 visited set 防御
 */
export function buildThreads(records: NoteDbCommentRecord[]): NoteDbThread[] {
  if (!Array.isArray(records) || records.length === 0) return [];

  const byUuid = new Map<string, NoteDbCommentRecord>();
  for (const r of records) {
    if (r?.key?.uuid) byUuid.set(r.key.uuid, r);
  }

  // 子节点索引
  const childrenByParent = new Map<string, NoteDbCommentRecord[]>();
  for (const r of records) {
    if (r.parentUuid && byUuid.has(r.parentUuid)) {
      const list = childrenByParent.get(r.parentUuid) ?? [];
      list.push(r);
      childrenByParent.set(r.parentUuid, list);
    }
  }

  // 找 root：无 parentUuid 或 parentUuid 指向不存在的 uuid（数据损坏兜底）
  const roots = records.filter(
    (r) => !r.parentUuid || !byUuid.has(r.parentUuid),
  );

  const threads: NoteDbThread[] = [];
  for (const root of roots) {
    const chain: NoteDbCommentRecord[] = [];
    const visited = new Set<string>();
    const stack: NoteDbCommentRecord[] = [root];
    while (stack.length > 0) {
      const cur = stack.pop()!;
      if (visited.has(cur.key.uuid)) continue;
      visited.add(cur.key.uuid);
      chain.push(cur);
      const kids = childrenByParent.get(cur.key.uuid) ?? [];
      stack.push(...kids);
    }
    chain.sort((a, b) => {
      if (a.writtenOn < b.writtenOn) return -1;
      if (a.writtenOn > b.writtenOn) return 1;
      // writtenOn 相同（极少见）按 uuid 字典序保证稳定
      return a.key.uuid < b.key.uuid ? -1 : a.key.uuid > b.key.uuid ? 1 : 0;
    });
    const latest = chain[chain.length - 1];
    threads.push({
      root,
      chain,
      latest,
      is_unresolved: latest.unresolved === true,
    });
  }
  return threads;
}
